export enum IngredientUnity {
  UNITE = 'unité(s)',
  PAQUET = 'paquet(s)',
  TRANCHE = 'tranche(s)',
  GRAMME = 'g',
  KILOGRAMME = 'kg',
  MILLILITRE = 'ml',
  CENTILITRE = 'cl',
  LITRE = 'l',
  CUILLERE_A_CAFE = 'c-à-c',
  CUILLERE_A_SOUPE = 'c-à-s',
  BOITE = 'boite(s)',
  BOUTEILLE = 'bouteille(s)',
  POT = 'pot(s)',
  PINCE = 'pincée(s)',
}
