export enum IngredientCategory {
  OTHER = 'Other',
  MEATS = 'Meats',
  STARCHES = 'Starches',
  DRINKS = 'Drinks',
  FRUITS_VEGETABLES = 'Fruits & Vegetables',
  DAIRY_PRODUCTS = 'Dairy Products',
  DAILY_PRODUCTS = 'Daily Products',
  SEASONINGS = 'Seasonings',
  SEAFOOD = 'Seafood',
  BAKERY = 'Bakery',
  SWEETS = 'Sweets',
  FROZEN = 'Frozen',
  CANNED = 'Canned',
  SAUCES = 'Sauces',
  SNACKS = 'Snacks',
}
